apiVersion: v1
kind: Service
metadata:
  name: {solutionShortName}-service
spec:
  type: NodePort
  selector:
    app: {solutionShortName}
  ports:
    - port: {port}
      targetPort: {port}
      nodePort: {nodePort}
